### ISSUE TITLE
does not do upgrade of snap

### ISSUE THREAD

**Issue by max-chudnovsky** [root-expert/puppet-snap#23]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 7
- Ruby: 2.7
- Distribution: bullseye 11
- Module version: 1.1.1

## How to reproduce (e.g Puppet code you use)
I declare the package in my module this way.  it works fine to install it.

  package { 'microk8s':
    ensure          => installed,
    provider        => 'snap',
    install_options => ['classic', 'channel=1.26'],
  }

then i go back to the module, change the channel to 1.27

  package { 'microk8s':
    ensure          => installed,
    provider        => 'snap',
    install_options => ['classic', 'channel=1.27'],
  }

running "puppet agent -t" does nothing.  I know my module gets executed as it does notice, but snap is not updated.  If I remove it manually with "snap remove microk8s" from the node, and then run "puppet agent -t" then it will install 1.27.

## What behaviour did you expect instead
it is supposed to do a snap refresh and update snap from 1.26 to 1.27

**Comment by root-expert** [comment]
Hey @max-chudnovsky ,

I believe the channels on microk8s snap are defined as `1.27/stable`. Take a look [here](https://microk8s.io/docs/setting-snap-channel)

**Comment by max-chudnovsky** [comment]
sorry, I could not wait so I wrote my provider.  Snaps should use "install"
only when you add a new snap.  If you want to change the channel, you need
to use "refresh".  Your module would install the module, but if I changed
the version it was not doing anything.  In any case, good luck with your
module.
